stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_IMAGE_BUILT_TAG: ${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  CONFIG_REPO_NAME: uniswap-statistics-api-configs

# ============= Build ==============
.build-head: &build-head
  stage: build
  image: ds414/gkecli-kube-helm
  services:
  - docker:dind

# build container image
build_uniswap_fetchers:
  <<: *build-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - cp ./${CONFIG_REPO_NAME}/Uniswap.Fetchers/* ./src/Uniswap.Fetchers
  - deployment/updateconfigs.sh Uniswap.Fetchers None
  - deployment/build.sh uniswap-fetchers Uniswap.Fetchers
  only:
  - master
  - develop

# build container image
build_uniswap_statistics-api:
  <<: *build-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - cp ./${CONFIG_REPO_NAME}/Uniswap.Statistics.Api/* ./src/Uniswap.Statistics.Api
  - deployment/updateconfigs.sh Uniswap.Statistics.Api Content
  - deployment/build.sh uniswap-statistics-api Uniswap.Statistics.Api
  only:
  - master
  - develop


# ============= Deploy =============
# ------------ STAGING ----------
.deploy-head: &deploy-head
  stage: deploy
  image: ds414/gkecli-kube-helm

# deploy to environment: staging
deploy_uniswap_fetchers_staging:
  <<: *deploy-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - deployment/deploy.sh uniswap-fetchers staging 
  environment:
    name: staging
  only:
  - develop

# deploy to environment: staging
deploy_uniswap_statistics_api_staging:
  <<: *deploy-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - deployment/deploy.sh uniswap-statistics-api staging 
  environment:
    name: staging
  only:
  - develop

# ------------ PROD ----------
# deploy to production environment
deploy_uniswap_fetchers_prod:
  <<: *deploy-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - deployment/deploy.sh uniswap-fetchers prod
  environment:
    name: staging
  only:
  - master

# deploy to production environment
deploy_uniswap_statistics_api_prod:
  <<: *deploy-head
  script:
  - apk add --update git
  - git clone ${GITLAB_CREDITIALS}
  - cp -r ./${CONFIG_REPO_NAME}/deployment ./
  - deployment/deploy.sh uniswap-statistics-api prod
  environment:
    name: staging
  only:
  - master




